// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsmclJ5T4RpSoxPlBElx1b2IIWafwRME8',
    appId: '1:1078411658463:web:ecfb3713c503ebe53d556a',
    messagingSenderId: '1078411658463',
    projectId: 'friends-of-hch',
    authDomain: 'friends-of-hch.firebaseapp.com',
    storageBucket: 'friends-of-hch.firebasestorage.app',
    measurementId: 'G-KB3H11G8EH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbSYRdv-P-4KZwIv_bjZtDDJHD2y26ebk',
    appId: '1:1078411658463:android:f9aeb5ca34922f573d556a',
    messagingSenderId: '1078411658463',
    projectId: 'friends-of-hch',
    storageBucket: 'friends-of-hch.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuCnJFhtTbS7Df4ZiwbsoVPUpJ-XdRXNs',
    appId: '1:1078411658463:ios:97bb563c6e04181d3d556a',
    messagingSenderId: '1078411658463',
    projectId: 'friends-of-hch',
    storageBucket: 'friends-of-hch.firebasestorage.app',
    iosBundleId: 'com.example.friendsHch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuCnJFhtTbS7Df4ZiwbsoVPUpJ-XdRXNs',
    appId: '1:1078411658463:ios:97bb563c6e04181d3d556a',
    messagingSenderId: '1078411658463',
    projectId: 'friends-of-hch',
    storageBucket: 'friends-of-hch.firebasestorage.app',
    iosBundleId: 'com.example.friendsHch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsmclJ5T4RpSoxPlBElx1b2IIWafwRME8',
    appId: '1:1078411658463:web:ad2e0b933285c4593d556a',
    messagingSenderId: '1078411658463',
    projectId: 'friends-of-hch',
    authDomain: 'friends-of-hch.firebaseapp.com',
    storageBucket: 'friends-of-hch.firebasestorage.app',
    measurementId: 'G-ZRRYJRVEW8',
  );
}
